# Generated by Django 5.0 on 2025-07-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
